[project]
name = "gw2-addon-manager"
version = "0.0.2"
description = "A simple tool to manage addons for Guild Wars 2."

requires-python = ">=3.11"

readme = "README.md"
dependencies = [
    "ruamel-yaml>=0.18.14",
]
