[project]
name = "gw2-addon-manager"
version = "0.0.3"
description = "A simple tool to manage addons for Guild Wars 2."

requires-python = ">=3.11"

readme = "README.md"
dependencies = [
    "requests>=2.32.4",
    "ruamel-yaml>=0.18.14",
    "types-requests>=2.32.4.20250611",
]
