version: 1
disable_existing_loggers: no
root:
  level: INFO
  handlers: [file]
loggers:
  api:
    level: INFO
    handlers: [file]
    propagate: no
  gui:
    level: INFO
    handlers: [file]
    propagate: no
  parser:
    level: INFO
    handlers: [file]
    propagate: no
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: report.log
    encoding: utf8
    maxBytes: 100000
    backupCount: 2
    formatter: standard
formatters:
  standard:
    style: "{"
    format: "{levelname: <8} | {asctime} | {name: <16} | {funcName}({lineno}): {message}"
    datefmt: "%Y-%m-%d %H:%M:%S"
