name: Bump Current Version

# Automatically bump the pyproject.toml and corresponding uv.lock file's minor
# version when a PR is created for src changes.
on:
  workflow_dispatch:

  pull_request:
    types: [ opened ]
    paths: [ src/** ]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    name: Bump pyproject.toml Version

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
          gpg_private_key: ${{ secrets.GPG_WORKFLOW_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_WORKFLOW_PASSPHRASE }}
          fingerprint: ${{ secrets.GPG_WORKFLOW_SUBKEY }}
          trust_level: 4 # Full

      - name: Configure Git for Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ steps.gpg.outputs.email }}"
          git config user.signingkey ${{ steps.gpg.outputs.keyid }}
          git config commit.gpgsign true

        # If no tags exist use the existing version - otherwise bump minor
      - name: Bump Version
        run: |
          echo "Existing Tags..."
          git tag --list

          version="v$(uv version --short)"
          echo "Current version: $version"
          if [[ -n $(git tag --list $version) ]]; then
            uv version --bump minor
          else
            echo "Skipping: $version not in tags."
          fi

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Workflow Bot 🤖: Version Bump"
          git push
