name: Bump Current Version

# Automatically bump the pyproject.toml and corresponding uv.lock file's minor
# version when a PR is created for src changes.
on:
  workflow_dispatch:

  pull_request:
    types: [ opened ]
    paths: [ src/** ]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    name: Bump pyproject.toml Version

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    env:
      BRANCH: ${{ github.head_ref || github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: Configure Git
        run: |
          git config core.autocrlf input
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # If no tags exist use the existing version - otherwise bump minor
      - name: Bump Version
        id: bump
        run: |
          echo "Existing Tags..."
          git tag --list

          version="v$(uv version --short)"
          echo "Current version: $version"

          bumped=false
          if [[ -n $(git tag --list $version) ]]; then
            uv version --bump minor
            git add --verbose .
            bumped=true
          else
            echo "Skipping: $version not in tags."
          fi

          echo "bumped=$bumped" >> $GITHUB_OUTPUT

      - name: Signed Commit (GraphQL API)
        if: steps.bump.outputs.bumped
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          COMMIT_MESSAGE="Workflow Bot 🤖: Version Bump"

          fields=(
            "-F query='@.github/api/createCommitOnBranch.gql'"
            "-F githubRepository=$GITHUB_REPOSITORY"
            "-F branchName=$BRANCH"
            "-F expectedHeadOid=$(git rev-parse HEAD)"
            "-F commitMessage='$COMMIT_MESSAGE'"
          )
          for filename in $(git diff --staged --name-only); do
            encoded_filename="b64${filename%.*}.txt"
            base64 -w 0 "$filename" > $encoded_filename
            fields+=(
              "-F files[][path]=$filename"
              "-F files[][contents]=@$encoded_filename"
            )
          done

          gh api graphql "${fields[@]}"
