name: Bump Current Version

on:
  workflow_dispatch:
    inputs:
      target:
        description: The target branch you want to bump the version on.
        type: string
        default: jhinze/

  pull_request:
    branches-ignore: [ main ]
    types: [ opened ]

jobs:
  bump_version:
    name: Bump pyproject.toml Version

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: Bump Version
        run: uv version --bump minor

      - uses: planetscale/ghcommit-action@6a383e778f6620afde4bf4b45069d3c6983c1ae2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          commit_message: "🤖 Version Bump"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}

      - name: Push Changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          branch: ${{ github.head_ref || github.ref }}
