name: Bump Current Version

# Automatically bump the pyproject.toml and corresponding uv.lock file's minor
# version when a PR is created for src changes.
on:
  workflow_dispatch:

  pull_request:
    branches-ignore: [ main ]
    types: [ opened ]
    paths: [ src/** ]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    name: Bump pyproject.toml Version

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

        # If no tags exist use the existing version - otherwise bump minor
      - name: Bump Version
        run: |
          echo "Existing Tags..."
          git tag --list

          version="v$(uv version --short)"
          echo "Current version: $version"
          if [[ -n $(git tag --list $version) ]]; then
            uv version --bump minor
          else
            echo "Skipping: $version not in tags."
          fi

      - name: Commit and Push changes
        uses: planetscale/ghcommit-action@6a383e778f6620afde4bf4b45069d3c6983c1ae2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          commit_message: "Workflow Bot 🤖: Version Bump"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref }}
