name: Bump Current Version

on:
  workflow_dispatch:

  pull_request:
    branches-ignore: [ main ]
    types: [ opened ]

jobs:
  bump_version:
    name: Bump pyproject.toml Version

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get Environment
        uses: .github/workflows/environment.yaml

      - name: Bump Version
        run: uv version --bump minor

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Version Bump"
          git push origin ${{ github.ref }} --dry-run
