name: Validate Code Changes

# Ensure that the latest code put into a PR builds the EXE successfully.
on:
  workflow_dispatch:

  workflow_call:
    outputs:
      run_id:
        description: Used to get artifacts from this run.
        value: ${{ github.run_id }}

  pull_request:
    types: [ opened, synchronize ]
    paths: [ src/** ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build EXE with PyInstaller

    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: Run PyInstaller
        run: uv run pyinstaller packaging.spec

      - name: Sign EXE
        uses: sigstore/gh-action-sigstore-python@f7ad0af51a5648d09a20d00370f0a91c3bdf8f84
        with:
          inputs: dist/${{ github.event.repository.name }}.exe

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ${{ github.sha }}
          path: dist/*
