name: Create New Tag

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ Validate Code Changes ]
    types: [ completed ]
    # branches: [ main ]
    branches: [ jhinze/* ]

jobs:
  create_tag:
    name: Create next Release tag

    if: |
      ( github.event.workflow_run.conclusion == 'success'
        && github.event.workflow_run.type == 'closed' )
      || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba

      - name: Handle Tagging
        id: tagger
        run: |
          version="v$(uv version --short)"
          if [[ -z $(git tag -l $version) ]]; then
            echo "Creating new tag: $version"
            git tag $version
            git push origin refs/tags/$version
          fi

          echo "tag=$version" >> $GITHUB_OUTPUT

    outputs:
      tag: ${{ steps.tagger.outputs.tag }}
