name: Release

on:
  workflow_dispatch:
    inputs:
      create_tag:
        description: Generate a new tag for Release
        type: boolean
        default: true

  pull_request:
    branches: [ main ]
    types:
      - closed

permissions:
  contents: read

jobs:
  generate_tag:
    name: Create next Release tag

    if: ${{ success() }}
    needs: [ build_exe ]
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tagger.outputs.new_tag }}

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get tag metadata
        id: tagger
        uses: anothrNick/github-tag-action@1.73.0
        env:
          INITIAL_VERSION: "1.0.0"
          TAG_PREFIX: v
          DRY_RUN: true

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: "${{ steps.tagger.outputs.old_tag }}"

      - name: Create first tag
        id: first_tag
        if: ${{ !steps.check_tag.outputs.exists }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          CUSTOM_TAG: "v1.0.0"

      - name: Create next tag
        id: next_tag
        if: ${{ steps.check_tag.outputs.exists }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          TAG_PREFIX: v

