name: Release

on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: Release as Draft
        type: boolean
        default: false
      is_prerelease:
        description: Mark as Pre-Release
        type: boolean
        default: false
      create_tag:
        description: Generate a new tag for Release
        type: boolean
        default: true

  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read

jobs:
  build_exe:
    name: Build EXE with PyInstaller

    # if: github.event.pull_request.merged == true
    runs-on: windows-latest

    outputs:
      artifact_id: ${{ steps.upload_artifact.outputs.artifact-id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install uv
          uv sync

      - name: Run PyInstaller
        run: |
          uv run pyinstaller packaging.spec

      - name: Upload Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: dist/*

  generate_tag:
    name: Create next Release tag

    if: ${{ success() }}
    needs: [ build_exe ]
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tagN.outputs.new_tag || steps.tag1.outputs.new_tag }}

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INITIAL_VERSION: "1.0.0"
      TAG_PREFIX: v

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get tag metadata
        id: tagger
        uses: anothrNick/github-tag-action@1.73.0
        env:
          DRY_RUN: true

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: "${{ steps.tagger.outputs.old_tag }}"

      - name: Create first tag
        id: tag1
        if: ${{ steps.check_tag.outputs.exists == 'false' }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          CUSTOM_TAG: "${{ steps.tagger.outputs.old_tag }}"

      - name: Create next tag
        id: tagN
        if: ${{ steps.check_tag.outputs.exists == 'true' }}
        uses: anothrNick/github-tag-action@1.73.0

  create_release:
    name: Create Release with Artifacts

    if: ${{ success() }}
    needs: [ build_exe, generate_tag ]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids:
            - ${{ needs.build_exe.outputs.artifact_id }}

      - name: Create Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ needs.generate_tag.outputs.tag }}
          release_name: ${{ needs.generate_tag.outputs.tag }}
          body: |
            Testing body.
            Will need to move to `body_path` soon.
          draft: ${{ inputs.is_draft || true }} # for now
          prerelease: ${{ inputs.is_prerelease || true }} # for now

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.download_artifacts.outputs.download-path }}
          asset_name: ${{ github.event.repository.name }}
          asset_content_type: application/zip
