name: Create New Release

on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: Release as Draft
        type: boolean
        default: false
      is_prerelease:
        description: Mark as Pre-Release
        type: boolean
        default: false
      create_tag:
        description: Generate a new tag for Release
        type: boolean
        default: true

  pull_request:
    branches: [ main ]
    types: [ closed ]

env:
  ARTIFACT_NAME: ${{ github.sha }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build_exe:
    name: Build EXE with PyInstaller

    # if: github.event.pull_request.merged == true # FIXME
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install uv
          uv sync

      - name: Run PyInstaller
        run: uv run pyinstaller packaging.spec

      - name: Sign EXE
        uses: sigstore/gh-action-sigstore-python@f7ad0af51a5648d09a20d00370f0a91c3bdf8f84
        with:
          inputs: dist/${{ env.REPO_NAME }}.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/*

  create_release:
    name: Create Release

    if: ${{ success() }}
    needs: [ build_exe ]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Test python-semantic-release
        uses: python-semantic-release/python-semantic-release@f9e152fb36cd2e590fe8c2bf85bbff08f7fc1c52
        with:
          build: false
          commit: true
          push: true
          tag: true
