name: Release

on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: Release as Draft
        type: boolean
        default: false
      is_prerelease:
        description: Mark as Pre-Release
        type: boolean
        default: false
      create_tag:
        description: Generate a new tag for Release
        type: boolean
        default: true

  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read

env:
  ARTIFACT_NAME: ${{ github.sha }}
  RELEASE_ARTIFACT: "${{ github.event.repository.name }}.zip"

jobs:
  build_exe:
    name: Build EXE with PyInstaller

    # if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install uv
          uv sync

      - name: Run PyInstaller
        run: uv run pyinstaller packaging.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: $ARTIFACT_NAME
          path: dist/*

  generate_tag:
    name: Create next Release tag

    if: ${{ success() }}
    needs: [ build_exe ]
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tagN.outputs.new_tag || steps.tag1.outputs.new_tag }}

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INITIAL_VERSION: "1.0.0"
      TAG_PREFIX: v

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get tag metadata
        id: tagger
        uses: anothrNick/github-tag-action@1.73.0
        env:
          DRY_RUN: true

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: "${{ steps.tagger.outputs.old_tag }}"

      - name: Create first tag
        id: tag1
        if: ${{ steps.check_tag.outputs.exists == 'false' }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          CUSTOM_TAG: "${{ steps.tagger.outputs.old_tag }}"

      - name: Create next tag
        id: tagN
        if: ${{ steps.check_tag.outputs.exists == 'true' }}
        uses: anothrNick/github-tag-action@1.73.0

  create_release:
    name: Create Release with Artifacts

    if: ${{ success() }}
    needs: [ build_exe, generate_tag ]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          name: $ARTIFACT_NAME

      - name: Check 1
        run: ls -hAlt

      - name: Zip Artifacts
        run: zip -r "$RELEASE_ARTIFACT" .

      - name: Check 2
        run: ls -hAlt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ inputs.is_draft || true }} # FIXME
          prerelease: ${{ inputs.is_prerelease || true }} # FIXME
          make_latest: true
          name: ${{ needs.generate_tag.outputs.tag }}
          tag_name: ${{ needs.generate_tag.outputs.tag }}
          body: |
            Test this.
            Move to `body_path` soon.
          generate_release_notes: true
          files: "$RELEASE_ARTIFACT"
