name: Create New Release

# If a tag was created - create a release.
on:
  workflow_dispatch:
    inputs:
      is_draft:
        description: Mark as Draft
        type: boolean
        default: true
      is_prerelease:
        description: Mark as Pre-Release
        type: boolean
        default: true

  workflow_run:
    workflows: [ Create New Tag ]
    types: [ completed ]
    branches-ignore: [ main ]

jobs:
  create_release:
    name: Create Release with Artifacts
    if: |
      github.event.workflow_run.conclusion == 'success'
      || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          ref: ${{ github.ref }}
          search_artifacts: true
          workflow: ci.yaml

      - name: Zip Artifacts
        run: zip -r ${REPO_NAME}.zip . -x *.sigstore.json

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          name: ${{ github.event.workflow_run.outputs.tag }}
          tag_name: ${{ github.event.workflow_run.outputs.tag }}
          generate_release_notes: true
          files: |
            ${{ env.REPO_NAME }}.zip
            *.sigstore.json
          draft: ${{ inputs.is_draft || true }} # FIXME
          prerelease: ${{ inputs.is_prerelease || true }} # FIXME
          make_latest: true
